# total revenue generated by each country sort by highest
select BillingCountry, sum(total) as total_revenue from 
invoice
GROUP By BillingCountry
ORDER BY total_revenue DESC;
# Average Invoice Value per Customer
SELECT c.FirstName,c.LastName,avg(i.Total) as Average
FROM customer c
LEFT JOIN invoice i 
on c.CustomerID = i.CustomerId
GROUP BY c.CustomerId,c.FirstName,c.LastName;
# customer with highest number of invoices
SELECT c.FirstName,c.LastName,count(i.InvoiceId) as Invoice_Count
FROM customer c
LEFT JOIN invoice i 
on c.CustomerID = i.CustomerId
GROUP BY c.CustomerId,c.FirstName,c.LastName
ORDER BY Invoice_Count DESC
LIMIT 3;